version: '3.8'

services:
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_CFG_NODE_ID=1
    volumes:
      - "kafka_data:/bitnami/kafka"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8085:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SMTP_PORT=465
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_LOGIN=
      - SMTP_PASSWORD=
      - KAFKA_SERVER=kafka:29092
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
      - "/app/.venv"
    command:
      [
        "poetry",
        "run",
        "start"
      ]

volumes:
  kafka_data:
    driver: local

networks:
  broker-kafka:
    driver: bridge
