version: '3.1'

services:
  postgres:
    image: postgres:16.2
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/postgres/data"
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=eshop
      - POSTGRES_DB=eshop_order

volumes:
  postgres_data:
    driver: local