version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'USER_SERVICE_HOST=http://localhost:8080'
      - 'ORDER_SERVICE_HOST=http://localhost:50000'
    ports:
      - "8081:8081"